#!/bin/sh
# -*- sh -*-
set -e

complain() {
    echo 1>&2
    echo "### $@" 1>&2
    echo 1>&2
}

die() {
    test -f progress && cat progress
    rm progress
    complain "$@"
    exit 1
}

report() {
    test -f report || return 0
    v=`grep "^$1:" report | cut -f2- -d: | cut -c2-`
    if test -n "$2" && test "$2" != "$v"; then
        complain "Field $1: expected '$2'; got '$v'"
        return 1
    fi
    echo "$v";
    return 0
}

ltl_valid() {
    report Finished Yes
    report Property-Type neverclaim || return 0
    report Property-Holds Yes
}

ltl_invalid() {
    report Finished Yes
    report Property-Type neverclaim || return 0
    report Property-Holds No
}

reachability_valid() {
    report Finished Yes
    report Property-Type reachability || return 0
    report Property-Holds Yes
}

reachability_deadlock() {
    report Finished Yes
    report Property-Type reachability || return 0
    report Property-Holds No
    report CE-Type deadlock
}

reachability_goal() {
    report Finished Yes
    report Property-Type reachability || return 0
    report Property-Holds No
    report CE-Type goal
}

reachability_any() {
    report Finished Yes
    report Property-Type reachability || return 0
    report Property-Holds No
    report CE-Type goal || report CE-Type deadlock
}

statespace() {
    test -f report || return 0

    report Finished Yes
    op=-eq
    report Full-State-Space No && op=-le
    grep "^Transformations:.*POR" report && op=-le

    states=`report States-Visited`
    trans=`report Transition-Count`
    accept=`report States-Accepting`
    dead=`report Deadlock-Count`

    test $states $op $1 || die "States-Visited: $1 expected, $states got"
    test "$trans" = "-" || test $trans $op $2 || die "Transition-Count: $2 expected, $trans got"
    test $accept $op $3 || die "States-Accepting: $3 expected, $accept got"
    test "$dead" = "-" || test $dead $op $4 || die "Deadlock-Count: $4 expected, $dead got"
}

clear() {
    rm -f progress report
}

owcty_sizes() {
    test -f report || return 0
    test -f progress || return 0

    if ! grep -q "^Algorithm: OWCTY" report; then return 0; fi
    if grep -q "^Full-State-Space: No" report; then return 0; fi
    if grep -q "^Transformations:.*POR" report; then return 0; fi

    grep '|S| = ' progress | sed -r -e 's,[^0-9]*([0-9]+).*,\1,' > numbers
    rm -f numbers-right
    for n in $@; do echo $n >> numbers-right; done
    diff -u numbers-right numbers
}

debris() {
    echo
    test -f progress && cat progress || true
}

"$@"
