#!/bin/sh
cd $(dirname $0)/..
if test -z "$DIVBENCH_DB"; then
    export DIVBENCH_DB="Driver={PostgreSQL};Database=divbench;Server=anna;ByteaAsLongVarBinary=1"
fi

divbench=$(make show var=OBJ)bench/tools/divbench
export OBJ=$(make show var=OBJ)
make divbench
./test/runner --export | $divbench import

echo "delete from model_tags where (select count(*) from tag where name like 'pthread_%' and model_tags.tag = tag.id) > 0;" | psql -h anna divbench
