#!/bin/sh
cd $(dirname $0)/..
if test -z "$DIVBENCH_DB"; then
    export DIVBENCH_DB="Driver={PostgreSQL};Database=divbench;Server=anna;ByteaAsLongVarBinary=1"
fi

divbench=$(make show var=OBJ)bench/tools/divbench
make divbench
./test/runner --export | $divbench import
