#!/bin/sh
set -e

gdb()
{
    test -e /usr/local/bin/egdb && exec /usr/local/bin/egdb --args "$@"
    test -e /usr/bin/gdb && exec /usr/bin/gdb --args "$@"
    echo "Could not find gdb."
    exit 1
}

cgdb() {
    /usr/bin/cgdb --args "$@"
}

memcheck() { exec valgrind --tool=memcheck "$@"; }

callgrind()
{
    exec env LD_BIND_NOW=1 valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes --separate-threads=yes "$@"
}

td=$(readlink -f $(dirname $0))
test -z "$td" && td="."
td="$td/.."

test -z "$B" && test "$DBG" = gdb && B=debug
test -z "$B" && test "$DBG" = callgrind && B=release
test -z "$B" && B=$(cd $td && make show var=DEFAULT_FLAVOUR)
test -z "$DBG" && DBG=exec
make -C $td $B-divine 1>&2
$DBG $(cd $td && make show var=OBJ)$B/tools/divine "$@"
