#!/bin/sh
# -*- sh -*-

if test "$1" = "--export"; then
    # divbench-import mode
    test -n "$SRCDIR" || export SRCDIR="$PWD"
    test -n "$BINDIR" || export BINDIR="${OBJ}debug"
    chmod +x test/lib/check
    . test/lib/verify $@
    exit $?
fi

# Prepares environment, switches to a temporary work directory
. lib/testcase

# Generates a script for the divcheck tool
verify --export $@ > dcscript

# Print the script when error occurs
cat dcscript | capture

divcheck dcscript
