#!/usr/bin/env bash
set -e -o pipefail
cat > sim.script
grep '^>' sim.script | cut -c3- | divine sim --batch "$@" 2>&1 | tee sim.out
echo; echo = expected ==========
cat sim.script
echo; echo = matched ===========
sed -e "s,^>,+ ^>," sim.script | check sim
