#!/bin/sh

./runner \
    --total-timeout 28800 --timeout 600  \
    --interpreter cpp:lib/verify \
    --interpreter c:lib/verify \
    --interpreter pkg:lib/pkg \
    --interpreter bt:lib/brick-test \
    --interpreter pdc:lib/pdclib-test \
    --skip "[.]pkg/" \
    --workdir . --outdir results \
    --sort-hint "/([0-9]*)[.][^/]+$" "$@"

EXIT=$?
test -n "$TESTHOOK" && $TESTHOOK
exit $EXIT
