#!/bin/sh

. ./environment
chmod +x $TESTS/lib/*-unpack $TESTS/lib/verify

todo=,todo
for arg in "$@"; do
    if test -n "$tags" && echo $arg | grep -q todo; then todo=; fi
    if test "$arg" = "--tags"; then tags=1; else tags=; fi
done
test -n "$TODO" && todo= && extra="--tags todo"

./runner "$@" \
    --total-timeout 28800 --timeout 600  \
    --expand pkg.c:lib/pkgc-unpack \
    --expand pkg.cpp:lib/pkgc-unpack \
    --expand bt:lib/brick-unpack \
    --interpreter cpp:lib/verify \
    --interpreter c:lib/verify \
    --interpreter pkg:lib/pkg \
    --interpreter pdc:lib/pdclib-test \
    --interpreter bld:lib/build \
    --flavour z3:sym,!float,!z3skip \
    --flavour stp:sym,!float \
    --flavour smtlib:sym,min \
    --flavour vanilla:!sym \
    --skip "[.]pkg/,[.]helper[.]" \
    --exclude-tags attic$todo \
    --workdir . --outdir results \
    $extra

EXIT=$?
test -n "$TESTHOOK" && $TESTHOOK
exit $EXIT
