#!/bin/sh
# -*- sh -*-

if test "$1" = "--export"; then
    EXPORT=1
    SRC_ROOT=.
    shift
    set -e
else
    test -e lib/testcase && SILENT=1 . lib/testcase
    EXPORT= # unset
fi
export EXPORT

run()
{
    if test -n "$EXPORT"; then echo "$@"; else echo "+ divine $@"; divine "$@"; fi
}

getopt() { perl -ne "print \$1 if (m,/\* $1: (.*?) \*/, or m,// $1: (.*?)\n,)" $2; }

tags=$(eval echo $(getopt TAGS $1))
opts=$(eval echo $(getopt VERIFY_OPTS $1))
args=$(eval echo $(getopt PROGRAM_OPTS $1))
ccopt=$(eval echo $(getopt CC_OPTS $1))
extrasrc=$(eval echo $(getopt EXTRA_SRCS $1))
expect=$(eval echo $(getopt EXPECT $1))
gtest=
skipcc=$(getopt SKIP_CC $1)

std=
echo "$1" | grep -q '.cpp$' && { echo $ccopts | grep -qv -- '-std'; } && std="-std=c++14"

if test -z "$EXPORT"; then
    if echo $tags | grep -q huge; then
        resources="--max-memory 80GiB --threads 2"
    elif echo $tags | grep -q big; then
        resources="--max-memory 16GiB --max-time 1800 --threads 2"
    else
        resources="--max-memory 4GiB --max-time 600 --threads 2"
    fi
    extra="--report-filename verify.out"
fi

if test "$(eval echo $(getopt USE_GTEST $1))" = 1; then
    gtest="$TESTS/lib/gtest/src/gtest-all.cc $TESTS/lib/gtest/src/gtest_main.cc -I$TESTS/lib/gtest -lm"
fi

if test -z "$EXPORT"; then
    if echo "$opts" | grep -q "symbolic"; then
        solver=$TEST_FLAVOUR
        if test $solver = z3 && test $OPT_Z3 = OFF; then skip; fi
        if test $solver = stp && test $OPT_STP = OFF; then skip; fi
        if test $solver = smtlib; then solver=$solver:z3; z3 --version > /dev/null || skip; fi
        if test $solver = vanilla; then solver=none; fi
        extra="$extra --solver $solver"
    elif ! echo "$opts" | egrep -q "leakcheck|relaxed"; then
        # --symbolic currently leaks memory
        extra="$extra --leakcheck exit"
    fi
fi

if test -n "$EXPORT"; then
    dir=$(dirname $1)
    name=$(basename $1)
    srcroot=$(readlink -f $(dirname $0)/../../)
    dios=$srcroot/dios
    incs="-isystem $dios/include -isystem $dios/libcxx/include"
    incs="$incs -I $srcroot/bricks"
    for f in $name $extrasrc; do
        deps=$(cd $dir && clang -I. $incs $std -MM -MT "" $f | sed -e 's,^: [^ ]*,,' -e 's,\\$,,')
        echo load $dir/$f $f
        for dep in $deps; do
            if ! echo $dep | grep -q '^/'; then dep=$dir/$dep; fi
            echo load $dep $(echo $dep | sed -e s,$srcroot/*,,)
        done
    done
    if test -z "$expect"; then
        check=$(readlink -f $(dirname $0)/check)
        (cd $dir ; $check verify $name)
    else
        echo "expect" "$expect"
    fi
else
    name="$1"
fi

if test "$skipcc" = 1; then
    run=$name
    opts="$std $opts"
else
    run cc -o testcase.bc $std $ccopt "$name" $gtest
    run=testcase.bc
fi

run verify $resources $extra $opts $run $args

if test -n "$EXPORT"; then exit 0; fi

err=$(grep "error found:" verify.out | cut -d' ' -f3- || true)
if [ "$err" = yes ]; then
    echo "+ divine sim --batch --skip-init --load-report verify.out"
    echo "backtrace" | \
        divine sim --batch --skip-init --load-report verify.out > sim.out 2>&1
fi

check verify "$name"

# vim: syntax=sh
